### ISSUE TITLE
cannot show any printer with software

### ISSUE THREAD

**Issue by newyorkthink** [anujdatar/cups-docker#14]
the printe have cups website
![image](https://github.com/anujdatar/cups-docker/assets/87791643/dd469b6f-ac70-4f56-85c9-e8190fd51c1f)

bud master pdf editor or other wps and any pdf software cannot detect print

you build is back
![image](https://github.com/anujdatar/cups-docker/assets/87791643/5cce1520-2e8d-4d8c-9ea4-e3f2201b5111)

any pdf software canot show it

**Comment by newyorkthink** [comment]
```
version: '3'
services:
  cups:
    image: anujdatar/cups
    container_name: cups
    restart: unless-stopped
    ports:
        - "631:631"
    devices:
        - /dev/bus/usb:/dev/bus/usb
    environment:
        - CUPSADMIN=admin
        - CUPSPASSWORD=admin
        - TZ="America/Gotham"
    volumes:
        - /etc/cups:/etc/cups

```
